example/main.go, manager/interfaces.go, manager/manager.go
This PR changes the public/exported interface (that consumers will implement) for the library to shift the responsibility for encoding to PEM to the implementor of the library.
This is to allow implementors to add e.g. trailing PEM comments (which are permitted by both the PEM spec and the Certificate(Signing)Request API). These may be used for any purpose, including (but not limited to) attaching additional attestation information that does not fit within the x509 document.
=> Expect PEM data to be returned by SignRequestFunc instead of DER

deploy/cert-manager-csi-driver.yaml, example/main.go, internal/api/consts.go, internal/api/util/hash.go, manager/manager.go, test/integration/issuance_test.go, test/util/testutil.go
This implements the cleanup portion of what's described in the `certificaterequest-management.md` design document.
It allows the driver to delete 'old' CertificateRequest resources (up to a configurable limit) to avoid creating an excessive number of resources, impacting the stability of the apiserver.
=> Support deleting/cleaning up CertificateRequest objects for volumes

SECURITY.md
Adds SECURITY.md as found in e.g.
- https://github.com/cert-manager/website/blob/master/SECURITY.md and
- https://github.com/cert-manager/istio-csr/blob/master/SECURITY.md
=> Add security reporting info for csi-lib

driver/nodeserver.go, manager/interfaces.go, manager/manager.go, storage/filesystem.go, storage/interfaces.go, storage/memory.go
This PR adds an optional option to the manager: `ClientForMetadata`. This takes a function which returns a cert-manager client based on the passed Volume metadata. This is designed to be used to generate on the fly cert-manager clients that make use of [CSI token requests](https://kubernetes-csi.github.io/docs/token-requests.html). CertificateRequests created by this client will then have the UserInfo of the pod who owns that Volume. This allows a CSI driver to request identity documents on the pods behalf, whilst an approver can validate the contents of the certificate request matches that of the pod.
By default this is unset, which means the `Client` cert-manager client will be used to create CertificateRequests.
I have modified the filesystems `RegisterMetadata` func so that it will …
=> Adds ClientForMatadataFunc to manager 

internal/api/consts.go, internal/api/util/hash.go
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
=> Adds missing copy write headers to internal go package files

manager/manager.go
This patch adds exponential back-off when issuance is required for a certificate.
This should not be merged yet as it needs more extensive testing (both automated and manual). I'm pushing it up to get some additional eyes on it, and in case anyone wants to test it out. I'm not too familiar with the exponential back-off functions in the `wait` package, and the numbers I have chosen to configure the back-off are a little hand wavy 😄
=> Add exponential back-off when issuance fails

manager/interfaces.go, manager/manager.go
Fixes spelling of our type and Manager field `ClientForMatadata` -> `ClientForMetadata`.
=> Fix spelling of manager interface ClientForMetadata

go.mod, manager/util/tokenrequest.go, manager/util/tokenrequest_test.go
This PR adds the `manager/util` package which is intended to include helper functions for csi-lib consumers.
`EmptyAudienceTokenFromMetadata` will return the empty audience request token from the volume context. This is useful for drivers who want to extract the Pod's ServiceAccount information without needed to GET Pods.
`ClientForMetadataTokenRequestEmptyAud` is intended to be plugged straight into `manager.ClientForMetadata` and will be used to generate cert-manager clients who authenticate to the API server using the Pod's ServiceAccount. 
I have ended up copying these funcs multiple times, so seems sensible to add these util helpers to csi-lib so other consumers don't have to write them themselves.
```release-note
NONE
```
=> Adds ClientForMetadataTokenRequestEmptyAud and EmptyAudienceTokenFromMetadata

driver/driver.go, driver/nodeserver.go, manager/interfaces.go, manager/manager.go, storage/filesystem.go, storage/memory.go, test/integration/ready_to_request_test.go, test/util/testutil.go
This will help facilitate https://github.com/cert-manager/csi-driver/issues/17 and any other uses where we want to permit the pod to startup even if the CSI driver is not yet ready.
This feature comes with the caveat that user applications/pods MUST be designed to tolerate certificate/private key data not being available when the pod first starts up (as the driver will no longer block pod startup until the volume _is_ ready to request a certificate).
=> Add option to skip blocking pod startup if driver is not ready to create a request yet

README.md
This matches the repo with others in the org
(see https://github.com/cert-manager/csi-driver/pull/80 for the reasons I've used the specific attributes)
=> Add cert-manager logo to readme

manager/manager.go
=> Change CertificateRequest owner reference of pod `core/v1` -> `v1`

manager/manager.go
It is not clear to me why a TODO context is being used for the issuing function. It seems clear to me that we would want to use the context which is cancelled when the stop channel is closed.
PR passes that context through to `issue`.
=> Use a passed through context to manager issue function

deploy/cert-manager-csi-driver.yaml, deploy/example/example-app.yaml, driver/nodeserver.go, manager/manager.go, test/integration/ready_to_request_test.go, test/util/testutil.go
This PR changes the internals of how the NodePublishVolume calls wait for an initial issuance of a Certificate.
Previously, a volume would be registered for management in the NodePublishVolume call, and then a `wait` function was used from the driver package to wait until the manager has successfully completed an issuance of the certificate.
This made it take longer for users to see errors if there are any (it'd always take a minimum of 30s to get errors) plus it has lead to poor handling of "backing off" in cases where requests continuously fail (see #30).
Instead, the driver will now attempt *one* issuance prior to beginning the long-running renewal loop in the manager, by using the new `ManageVolumeImmediate` method. This method:
1) registers the volume as under management (to prevent …
=> Simplify issuance backoff handling & improve error messages

manager/manager.go, test/integration/issuance_test.go, test/integration/ready_to_request_test.go
Since #35, we now rely on the next issuance time being set to properly 'resume' monitoring certificates after a driver restart.
Whilst we have always informed implementors to set the NextIssuanceTime field during their own `writeKeypair` implementation, we don't actually set this field in the core library.
This PR changes the issuance routine to explicitly default the NextIssuanceTime to be halfway through a certificate's lifetime. Implementors are free to override this default in their own `writeKeypair` function (and likely will/do). This serves as a default to avoid invalid/broken states from occurring (e.g. a certificate has been fully issued but the nextIssuanceTime is never set).
=> Default renewal time to halfway through certificates lifetime

manager/manager.go, manager/manager_test.go, manager/utils_test.go, test/driver/driver_testing.go, test/integration/issuance_test.go, test/integration/ready_to_request_test.go, test/util/testutil.go
This adds a selection of new unit tests for the manager, testing behaviour for handling failed requests as well as tests for the regular issuance path.
We also need to add tests to ensure *renewals* are triggered when expected - a similar pattern as defined here can be used for that, but for now I thought I'd get this in before the PR grows further 😄 
/assign @JoshVanL
=> Add more exhaustive unit testing for manager

manager/manager.go, test/integration/ready_to_request_test.go
Previously if the NextIssuanceTime was set to the epoch, ManageVolumeImmediate wouldn't actually block.
Fixes #41 
cc @7ing @JoshVanL
=> Make NodePublishVolume blocking if a volume is already ready to request

OWNERS, README.md
OWNERS files are going to be updated across the org to use teams instead following the biweekly meeting last week. This updates the OWNERS file here to match others first, though.
Also adds a godoc badge and tweaks the README because why not!
=> Add godoc badge, update OWNERS

go.mod, manager/util/tokenrequest_test.go
See: https://github.com/cert-manager/csi-lib/pull/37#discussion_r969744685
We have decided the not use the testify assert and require libraries for testing.
PR replaces use in `manager/utils` for stdlib.
=> Replace use of testify in manager/util in favour of stdlib

go.mod, manager/manager.go, manager/manager_test.go
The default renewal time calculation had a bug [here](https://github.com/cert-manager/csi-lib/blob/main/manager/manager.go#L425)- `duration * (2/3)` would always be 0 (integer division) so the certs would always be renewed 'now'.
This did not actually affect cert-manager/csi-driver and cert-manager/csi-driver-spiffe as both had their own calculation of renewal time that was overriding this value see [here](https://github.com/cert-manager/csi-driver/blob/main/pkg/filestore/writer.go#L118) and [here](https://github.com/cert-manager/csi-driver-spiffe/blob/d71c5a9e6a465b3bb6ba4006879ffd84ecbd52e2/internal/csi/driver/util.go#L52).
The new function and test are adopted from the csi-driver/csi-driver-spiffe examples linked above.
=> Fix default renewal time calculation

manager/manager.go, manager/manager_test.go, test/driver/driver_testing.go
Add an internal parameter to control issue() call during renewal:
- issueRenewalTimeout: default 60s to align with NodePublishVolume timeout value
This fix prevents inifite loop in a single issue() call when CertificateRequest is in a pending state.
fixes: #45
=> Add timeout to renewal issuance logic

manager/manager.go, manager/manager_test.go, test/driver/driver_testing.go, test/integration/resume_request_test.go
replaces #48 
Some issuers take a very long time to approve and issue a certificate request. Because the CSI drivers NodePublishVolume call has its own implicit timeout (1 minute) which cannot be changed easily, we would like to be able to 'resume' a request even if it has taken longer than 1 minute to complete.
As a concrete example, say an issuer *always* takes 90s to complete a request (for whatever reason). In these cases, the driver will wait 60s, the context will timeout, 30s later the request will be issued, but upon the NodePublishVolume call being retried we will continuously create a new request.
This is obviously not desirable, so persisting a reference to the `crypto.PrivateKey` in memory allows us to 'resume' the request if it is still usable.
This is different to #48 in that …
=> add pending request cache to allow for resuming in-flight requests that take longer than a single issuance cycle

storage/filesystem.go, storage/filesystem_test.go
fixes #58 and also switches us to using 'Stat' rather than 'Open'
=> if a volume containing incomplete metadata is found during a ListVolumes call, clean up and continue
